<a href="https://colab.research.google.com/github/sasireddyvari/LifeCycle_DataScience/blob/master/Hypothesis_Testing.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**Hypothesis Testing :**
Inferial Statistics
1.   T Test :
        *  One sample (One Numerical / Categorical)- ttest_1samp
        *  Two Sample (Two Numerical variable) - ttest_ind
        *  Paired T Test - ttest_rel
2.   Chi Square test : Two Categorical
3.   Annova test : Two or more Categorical

**Problem Statement:**

Is the sample mean and population mean different or not?

In [11]:
import numpy as np
import pandas as pd
import scipy.stats as stats
import math

In [1]:
ages=[10,20,35,50,28,40,55,18,16,55,30,25,43,18,30,28,14,24,16,17,32,35,26,27,65,18,43,23,21,20,19,70]  

In [2]:
ages_mean=np.mean(ages)
print(ages_mean)

30.34375


In [3]:
sample_size=10
age_sample=np.random.choice(ages,sample_size)

In [4]:
age_sample

array([21, 18, 40, 10, 24, 55, 35, 10, 30, 20])

In [5]:
from scipy.stats import ttest_1samp

In [6]:
ttest,p_value= ttest_1samp(age_sample,ages_mean)

In [7]:
print(ttest,p_value)

-0.9107863323567299 0.3861516951831093


In [9]:
if p_value < 0.05:
  print('we are rejecting the Null Hypothesis: There is no difference between Sample Mean and Population Mean') # No difference between Sample Mean and Population Mean
else:
  print('we are accepting the Null Hypothesis:There is no difference between Sample Mean and Population Mean') # there is difference between Sample Mean and Population Mean

we are accepting the Alternate Hypothesis:There is difference between Sample Mean and Population Mean


**Problem Statement:**

Is the sample means of two continuous variables and respecive population means different or not?

In [14]:
np.random.seed(6)
classA_ages=stats.poisson.rvs(loc=18,mu=30,size=60)
classA_ages.mean()

48.016666666666666

In [12]:
np.random.seed(12)
ClassB_ages=stats.poisson.rvs(loc=18,mu=33,size=60)
ClassB_ages.mean()

50.63333333333333

In [19]:
ttest2,p_value=stats.ttest_ind(a=classA_ages,b=ClassB_ages,equal_var=False)
p_value

0.017232336215211357

In [22]:
if p_value < 0.05:    # alpha value is 0.05 or 5%
    print(" we are rejecting null hypothesis:i.e There is no diff between sample means with their populations")
else:
    print("we are accepting null hypothesis: there is no diff between sample means with their populations")

 we are rejecting null hypothesis: there is no diff between sample means with their populations


**Correlation**

In [23]:
import seaborn as sns
df=sns.load_dataset('iris')

In [25]:
df.corr()

sepal_length  sepal_width  petal_length  petal_width
sepal_length      1.000000    -0.117570      0.871754     0.817941
sepal_width      -0.117570     1.000000     -0.428440    -0.366126
petal_length      0.871754    -0.428440      1.000000     0.962865
petal_width       0.817941    -0.366126      0.962865     1.000000

**Chi Square Test**

In [32]:
dataset=sns.load_dataset('tips')
dataset.head()

total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [29]:
dataset.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
dtype: int64

In [35]:
dataset.day.value_counts()

Sat     87
Sun     76
Thur    62
Fri     19
Name: day, dtype: int64

In [36]:
dataset.corr()

total_bill       tip      size
total_bill    1.000000  0.675734  0.598315
tip           0.675734  1.000000  0.489299
size          0.598315  0.489299  1.000000

In [37]:
dataset_table=pd.crosstab(dataset['sex'],dataset['smoker'])
print(dataset_table)

smoker  Yes  No
sex            
Male     60  97
Female   33  54


In [38]:
dataset_table.values 

array([[60, 97],
       [33, 54]])

In [39]:
Observed_Values = dataset_table.values 
print("Observed Values :\n",Observed_Values)

Observed Values :
 [[60 97]
 [33 54]]


In [41]:
val=stats.chi2_contingency(dataset_table)
val

(0.008763290531773594, 0.925417020494423, 1, array([[59.84016393, 97.15983607],
        [33.15983607, 53.84016393]]))

In [43]:
Expected_Values=val[3]
Expected_Values

array([[59.84016393, 97.15983607],
       [33.15983607, 53.84016393]])

In [44]:
no_of_rows=len(dataset_table.iloc[0:2,0])
no_of_columns=len(dataset_table.iloc[0,0:2])
ddof=(no_of_rows-1)*(no_of_columns-1)
print("Degree of Freedom:-",ddof)
alpha = 0.05

Degree of Freedom:- 1


In [46]:
from scipy.stats import chi2
chi_square=sum([(o-e)**2./e for o,e in zip(Observed_Values,Expected_Values)])
chi_square_statistic=chi_square[0]+chi_square[1]

In [47]:
chi_square

array([0.00119737, 0.00073745])

In [48]:
chi_square_statistic

0.001934818536627623

In [49]:
critical_value=chi2.ppf(q=1-alpha,df=ddof)
print('critical_value:',critical_value)

critical_value: 3.841458820694124


In [50]:
p_value=1-chi2.cdf(x=chi_square_statistic,df=ddof)
print('p-value:',p_value)
print('Significance level: ',alpha)
print('Degree of Freedom: ',ddof)
print('p-value:',p_value)

p-value: 0.964915107315732
Significance level:  0.05
Degree of Freedom:  1
p-value: 0.964915107315732


In [55]:
if chi_square_statistic>=critical_value:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Accept H0,There is no relationship between 2 categorical variables")
    
if p_value<=alpha:
    print("Reject H0,There is a relationship between 2 categorical variables")
else:
    print("Accept H0,There is no relationship between 2 categorical variables")

Accept H0,There is no relationship between 2 categorical variables
Accept H0,There is no relationship between 2 categorical variables
