<a href="https://colab.research.google.com/github/sasireddyvari/LifeCycle_DataScience/blob/master/Python.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:
lst=[1,2,3]
lst

[1, 2, 3]

In [5]:
lst.append('4')

In [6]:
lst

[1, 2, 3, '4']

In [7]:
lst.extend([1,4])

In [8]:
lst

[1, 2, 3, '4', '1', '4']

In [9]:
lst.append([2,45])

In [13]:
lst.pop()

[2, 45]

In [15]:
lst

[1, 2, 3, '4', '1', '4']

In [22]:
lst=[1,2,3]
sum(lst)

6

In [23]:
lst=[1,2,3].extend([2,4])

In [26]:
type(lst)

NoneType

In [28]:
lst=[1,2,3]
type(lst)

list

In [29]:
lst.count(1)

1

In [32]:
lst=[3,4,56,1,6,7,2,4]
lst.sort()
lst

[1, 2, 3, 4, 4, 6, 7, 56]

In [34]:
lst.index(2)

1

In [38]:
lst.index(1,0,9) # Value, start index,end indx

0

In [45]:
set_var=set()
set_var={'Sasi','Kumar'}

In [46]:
set_var

{'Kumar', 'Sasi'}

In [47]:
set_var.add('Sasi')

In [48]:
set_var

{'Kumar', 'Sasi'}

In [49]:
set_var={'Sasi','Sasi',2,3,2}

In [50]:
set_var

{2, 3, 'Sasi'}

In [52]:
set_var={'sasi','Kumar','Sasi'}
set_var

{'Kumar', 'Sasi', 'sasi'}

In [66]:
dic={'Sasi':'Kumar',
      'A':3,
      6:'Sasi',
     'B':7,
     'a':8,
     'b':9,
     'sasi':4
      }

In [67]:
type(dict)

dict

In [68]:
dic

{6: 'Sasi', 'A': 3, 'B': 7, 'Sasi': 'Kumar', 'a': 8, 'b': 9, 'sasi': 4}

In [72]:
dic[6]

'Sasi'

In [75]:
dic.values()

dict_values(['Kumar', 3, 'Sasi', 7, 8, 9, 4])

In [76]:
dic.items()

dict_items([('Sasi', 'Kumar'), ('A', 3), (6, 'Sasi'), ('B', 7), ('a', 8), ('b', 9), ('sasi', 4)])

In [77]:
dic.keys()

dict_keys(['Sasi', 'A', 6, 'B', 'a', 'b', 'sasi'])

In [80]:
dic.update({'Sa':7})

In [81]:
dic

{6: 'Sasi',
 'A': 3,
 'B': 7,
 'Sa': 7,
 'Sasi': 'Kumar',
 'a': 8,
 'b': 9,
 'sasi': 4}

In [84]:
import numpy as np
lst=[1,2,3]
arr=np.array(lst)

In [85]:
arr

array([1, 2, 3])

In [86]:
type(arr)

numpy.ndarray

In [87]:
arr.shape

(3,)

In [88]:
arr1=[1,2,3]
arr2=[4,5,6]

In [90]:
arr=np.array([arr1,arr2])

In [91]:
arr.shape

(2, 3)

In [92]:
arr.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [97]:
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [94]:
arr[:,2]

array([3, 6])

In [95]:
arr[0:2,]

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
arr[0:2,0:2]

array([[1, 2],
       [4, 5]])

In [98]:
arr[1:,1:]

array([[5, 6]])

In [101]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [108]:
np.random.random_sample((40))

array([0.47967985, 0.56209385, 0.68103289, 0.30060848, 0.00563481,
       0.87827663, 0.60073865, 0.54449925, 0.83203017, 0.32855052,
       0.42290553, 0.07870533, 0.6415652 , 0.6567207 , 0.05773853,
       0.14435696, 0.46554328, 0.16902578, 0.02941339, 0.07065844,
       0.66455213, 0.92096119, 0.41600298, 0.58172919, 0.89235428,
       0.78070953, 0.92582205, 0.52941082, 0.83010578, 0.05457884,
       0.79733382, 0.37290856, 0.12882455, 0.38079612, 0.30359554,
       0.56813744, 0.75070396, 0.33733039, 0.02453844, 0.10734719])

In [110]:
arr=range(1,10)

In [111]:
arr

range(1, 10)

In [115]:
import pandas as pd
import numpy as np

In [119]:
df=pd.DataFrame(np.arange(0,20).reshape(5,4), index=['Row1','Row2','Row3','Row4','Row5'], columns=['c1','c2','c3','c4'])

In [120]:
df

c1  c2  c3  c4
Row1   0   1   2   3
Row2   4   5   6   7
Row3   8   9  10  11
Row4  12  13  14  15
Row5  16  17  18  19

In [121]:
df.loc['Row1']

c1    0
c2    1
c3    2
c4    3
Name: Row1, dtype: int64

In [123]:
df.iloc[0]

c1    0
c2    1
c3    2
c4    3
Name: Row1, dtype: int64

In [124]:
df.iloc[0:2,1:3]

c2  c3
Row1   1   2
Row2   5   6

In [125]:
type(df.iloc[0:2,1:3])

pandas.core.frame.DataFrame

In [129]:
type(df.iloc[0:1,0:])

pandas.core.frame.DataFrame

In [134]:
type(df.iloc[0:1,0])

pandas.core.series.Series

In [135]:
df.isnull().sum()

c1    0
c2    0
c3    0
c4    0
dtype: int64

In [136]:
df.c1.sum()

40

In [139]:
df.c1.value_counts()

12    1
4     1
16    1
8     1
0     1
Name: c1, dtype: int64

In [141]:
df[['c1','c2']]

c1  c2
Row1   0   1
Row2   4   5
Row3   8   9
Row4  12  13
Row5  16  17

In [142]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5 entries, Row1 to Row5
Data columns (total 4 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   c1      5 non-null      int64
 1   c2      5 non-null      int64
 2   c3      5 non-null      int64
 3   c4      5 non-null      int64
dtypes: int64(4)
memory usage: 360.0+ bytes


In [146]:
df.describe()

c1         c2         c3         c4
count   5.000000   5.000000   5.000000   5.000000
mean    8.000000   9.000000  10.000000  11.000000
std     6.324555   6.324555   6.324555   6.324555
min     0.000000   1.000000   2.000000   3.000000
25%     4.000000   5.000000   6.000000   7.000000
50%     8.000000   9.000000  10.000000  11.000000
75%    12.000000  13.000000  14.000000  15.000000
max    16.000000  17.000000  18.000000  19.000000

In [147]:
df.c1.unique()

array([ 0,  4,  8, 12, 16])

In [148]:
!unzip '/content/drive/MyDrive/Colab Notebooks/mercedes-benz-data-exploration.zip'

Archive:  /content/drive/MyDrive/Colab Notebooks/mercedes-benz-data-exploration.zip
   creating: mercedes-benz-data-exploration/
   creating: mercedes-benz-data-exploration/sample_submission.csv/
  inflating: mercedes-benz-data-exploration/sample_submission.csv/sample_submission.csv  
   creating: mercedes-benz-data-exploration/test.csv/
  inflating: mercedes-benz-data-exploration/test.csv/test.csv  
   creating: mercedes-benz-data-exploration/train.csv/
  inflating: mercedes-benz-data-exploration/train.csv/train.csv  


In [149]:
df=pd.read_csv('/content/mercedes-benz-data-exploration/train.csv/train.csv')

In [150]:
df.describe()

ID            y  ...         X384         X385
count  4209.000000  4209.000000  ...  4209.000000  4209.000000
mean   4205.960798   100.669318  ...     0.000475     0.001426
std    2437.608688    12.679381  ...     0.021796     0.037734
min       0.000000    72.110000  ...     0.000000     0.000000
25%    2095.000000    90.820000  ...     0.000000     0.000000
50%    4220.000000    99.150000  ...     0.000000     0.000000
75%    6314.000000   109.010000  ...     0.000000     0.000000
max    8417.000000   265.320000  ...     1.000000     1.000000

[8 rows x 370 columns]

In [154]:
df[df['y']<100]

ID      y  X0  X1  X2 X3 X4  ... X378 X379 X380  X382  X383  X384  X385
1        6  88.53   k   t  av  e  d  ...    0    0    0     0     0     0     0
2        7  76.26  az   w   n  c  d  ...    0    0    0     1     0     0     0
3        9  80.62  az   t   n  f  d  ...    0    0    0     0     0     0     0
4       13  78.02  az   v   n  f  d  ...    0    0    0     0     0     0     0
5       18  92.93   t   b   e  c  d  ...    0    0    0     0     0     0     0
...    ...    ...  ..  ..  .. .. ..  ...  ...  ...  ...   ...   ...   ...   ...
4197  8392  89.25   z   v  ae  c  d  ...    0    0    0     0     0     0     0
4198  8393  97.09  aw   a  ak  f  d  ...    0    0    0     0     0     0     0
4199  8395  88.24   t  aa  ay  c  d  ...    0    0    0     0     0     0     0
4203  8403  85.71  aq   s  as  c  d  ...    0    0    0     0     0     0     0
4207  8415  87.48  al   r   e  f  d  ...    0    0    0     0     0     0     0

[2203 rows x 378 columns]

In [167]:
data=('sasi,1,23,4\n'
      'kumar,2,3,4,5\n')

In [165]:
from io import StringIO,BytesIO
data=pd.read_csv(StringIO(data))
data

sasi  1  23  4
kumar     2  3   4  5

In [ ]:
data=('sasi,1,23,4\n'
      'kumar,2,3,4,5\n')

In [178]:
from io import StringIO,BytesIO
data=pd.read_csv(StringIO(data), dtype=object)

In [171]:
data

sasi  1 23  4
kumar    2  3  4  5

In [175]:
data['sasi']['kumar'] # 2 is a string

'2'

In [180]:
data.dtypes

sasi    object
1       object
23      object
4       object
dtype: object

In [183]:
data=('sasi,1,23,4\n'
      'kumar,2,3,4,5\n')

In [184]:
from io import StringIO,BytesIO
data=pd.read_csv(StringIO(data), dtype={'sasi':int,'1':float})

In [185]:
data.dtypes

sasi      int64
1       float64
23        int64
4         int64
dtype: object

In [186]:
df.dtypes

ID        int64
y       float64
X0       object
X1       object
X2       object
         ...   
X380      int64
X382      int64
X383      int64
X384      int64
X385      int64
Length: 378, dtype: object

In [187]:
df=pd.read_csv('/content/mercedes-benz-data-exploration/train.csv/train.csv',index_col=0)

In [188]:
df.head()

y  X0 X1  X2 X3 X4 X5  ... X378 X379  X380  X382  X383  X384  X385
ID                              ...                                        
0   130.81   k  v  at  a  d  u  ...    0    0     0     0     0     0     0
6    88.53   k  t  av  e  d  y  ...    0    0     0     0     0     0     0
7    76.26  az  w   n  c  d  x  ...    0    0     0     1     0     0     0
9    80.62  az  t   n  f  d  x  ...    0    0     0     0     0     0     0
13   78.02  az  v   n  f  d  h  ...    0    0     0     0     0     0     0

[5 rows x 377 columns]

In [193]:
df=pd.read_csv('/content/mercedes-benz-data-exploration/train.csv/train.csv')

In [192]:
len(df.ID.unique())

4209

In [198]:
df=pd.read_csv('/content/mercedes-benz-data-exploration/train.csv/train.csv',index_col=0)
df

y  X0 X1  X2 X3 X4  X5  ... X378 X379  X380  X382  X383  X384  X385
ID                                 ...                                        
0     130.81   k  v  at  a  d   u  ...    0    0     0     0     0     0     0
6      88.53   k  t  av  e  d   y  ...    0    0     0     0     0     0     0
7      76.26  az  w   n  c  d   x  ...    0    0     0     1     0     0     0
9      80.62  az  t   n  f  d   x  ...    0    0     0     0     0     0     0
13     78.02  az  v   n  f  d   h  ...    0    0     0     0     0     0     0
...      ...  .. ..  .. .. ..  ..  ...  ...  ...   ...   ...   ...   ...   ...
8405  107.39  ak  s  as  c  d  aa  ...    0    0     0     0     0     0     0
8406  108.77   j  o   t  d  d  aa  ...    0    0     0     0     0     0     0
8412  109.22  ak  v   r  a  d  aa  ...    0    0     0     0     0     0     0
8415   87.48  al  r   e  f  d  aa  ...    0    0     0     0     0     0     0
8417  110.85   z  r  ae  c  d  aa  ...    0    0     0     0     0     0     0

[4209 rows x 377 columns]

In [199]:
df.columns

Index(['y', 'X0', 'X1', 'X2', 'X3', 'X4', 'X5', 'X6', 'X8', 'X10',
       ...
       'X375', 'X376', 'X377', 'X378', 'X379', 'X380', 'X382', 'X383', 'X384',
       'X385'],
      dtype='object', length=377)

In [202]:
len(df.y.unique())

2545

In [203]:
# url to csv 
# Use sep='\t'

In [208]:
data='Hi Sais\n bdjs \nf\\jbjdbs\\db\njds\n'

In [207]:
data=pd.read_csv(StringIO(data),escapechar='\\')
data

Hi Sais
0       bdjs 
1  fjbjdbs\db
2         jds

In [219]:
#Json to csv
data = '{"employee_name": "James", "email": "james@gmail.com", "job_profile": [{"title1":"Team Lead", "title2":"Sr. Developer"}]}'
df1=pd.read_json(data)

In [244]:
df=pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/wine/wine.data', header=None)
df

0      1     2     3     4    5   ...    8     9      10    11    12    13
0     1  14.23  1.71  2.43  15.6  127  ...  0.28  2.29   5.64  1.04  3.92  1065
1     1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28   4.38  1.05  3.40  1050
2     1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81   5.68  1.03  3.17  1185
3     1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18   7.80  0.86  3.45  1480
4     1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82   4.32  1.04  2.93   735
..   ..    ...   ...   ...   ...  ...  ...   ...   ...    ...   ...   ...   ...
173   3  13.71  5.65  2.45  20.5   95  ...  0.52  1.06   7.70  0.64  1.74   740
174   3  13.40  3.91  2.48  23.0  102  ...  0.43  1.41   7.30  0.70  1.56   750
175   3  13.27  4.28  2.26  20.0  120  ...  0.43  1.35  10.20  0.59  1.56   835
176   3  13.17  2.59  2.37  20.0  120  ...  0.53  1.46   9.30  0.60  1.62   840
177   3  14.13  4.10  2.74  24.5   96  ...  0.56  1.35   9.20  0.61  1.60   560

[178 rows x 14 columns]

In [224]:
df1

employee_name  ...                                        job_profile
0         James  ...  {'title1': 'Team Lead', 'title2': 'Sr. Develop...

[1 rows x 3 columns]

In [225]:
df1.to_json()

'{"employee_name":{"0":"James"},"email":{"0":"james@gmail.com"},"job_profile":{"0":{"title1":"Team Lead","title2":"Sr. Developer"}}}'

In [221]:
df1.to_json(orient='records')

'[{"employee_name":"James","email":"james@gmail.com","job_profile":{"title1":"Team Lead","title2":"Sr. Developer"}}]'

In [227]:
df.to_json(orient='records')

'[{"0":1,"1":14.23,"2":1.71,"3":2.43,"4":15.6,"5":127,"6":2.8,"7":3.06,"8":0.28,"9":2.29,"10":5.64,"11":1.04,"12":3.92,"13":1065},{"0":1,"1":13.2,"2":1.78,"3":2.14,"4":11.2,"5":100,"6":2.65,"7":2.76,"8":0.26,"9":1.28,"10":4.38,"11":1.05,"12":3.4,"13":1050},{"0":1,"1":13.16,"2":2.36,"3":2.67,"4":18.6,"5":101,"6":2.8,"7":3.24,"8":0.3,"9":2.81,"10":5.68,"11":1.03,"12":3.17,"13":1185},{"0":1,"1":14.37,"2":1.95,"3":2.5,"4":16.8,"5":113,"6":3.85,"7":3.49,"8":0.24,"9":2.18,"10":7.8,"11":0.86,"12":3.45,"13":1480},{"0":1,"1":13.24,"2":2.59,"3":2.87,"4":21.0,"5":118,"6":2.8,"7":2.69,"8":0.39,"9":1.82,"10":4.32,"11":1.04,"12":2.93,"13":735},{"0":1,"1":14.2,"2":1.76,"3":2.45,"4":15.2,"5":112,"6":3.27,"7":3.39,"8":0.34,"9":1.97,"10":6.75,"11":1.05,"12":2.85,"13":1450},{"0":1,"1":14.39,"2":1.87,"3":2.45,"4":14.6,"5":96,"6":2.5,"7":2.52,"8":0.3,"9":1.98,"10":5.25,"11":1.02,"12":3.58,"13":1290},{"0":1,"1":14.06,"2":2.15,"3":2.61,"4":17.6,"5":121,"6":2.6,"7":2.51,"8":0.31,"9":1.25,"10":5.05,"11":1.06,"

In [230]:
df=pd.read_html('https://www.fdic.gov/bank/individual/failed/banklist.html')
df[0]

Bank Name  ...       Closing Date
0                    Almena State Bank  ...   October 23, 2020
1           First City Bank of Florida  ...   October 16, 2020
2                 The First State Bank  ...      April 3, 2020
3                   Ericson State Bank  ...  February 14, 2020
4     City National Bank of New Jersey  ...   November 1, 2019
..                                 ...  ...                ...
558                 Superior Bank, FSB  ...      July 27, 2001
559                Malta National Bank  ...        May 3, 2001
560    First Alliance Bank & Trust Co.  ...   February 2, 2001
561  National State Bank of Metropolis  ...  December 14, 2000
562                   Bank of Honolulu  ...   October 13, 2000

[563 rows x 6 columns]

In [232]:
url_mcc = 'https://en.wikipedia.org/wiki/Mobile_country_code'
dfs = pd.read_html(url_mcc, match='Country', header=0)
dfs[0]

Mobile country code  ...                   Remarks
0                    289  ...  MCC is not listed by ITU
1                    412  ...                       NaN
2                    276  ...                       NaN
3                    603  ...                       NaN
4                    544  ...                       NaN
..                   ...  ...                       ...
247                  452  ...                       NaN
248                  543  ...                       NaN
249                  421  ...                       NaN
250                  645  ...                       NaN
251                  648  ...                       NaN

[252 rows x 6 columns]

In [233]:
dfs = pd.read_html(url_mcc, match='National MNC authority', header=0)
dfs[0]


Mobile country code  ...                   Remarks
0                    289  ...  MCC is not listed by ITU
1                    412  ...                       NaN
2                    276  ...                       NaN
3                    603  ...                       NaN
4                    544  ...                       NaN
..                   ...  ...                       ...
247                  452  ...                       NaN
248                  543  ...                       NaN
249                  421  ...                       NaN
250                  645  ...                       NaN
251                  648  ...                       NaN

[252 rows x 6 columns]

In [248]:
df.to_excel('wine.xlsx')

In [250]:
df.to_pickle('wine')

In [251]:
df=pd.read_pickle('/content/wine')

In [252]:
df.head()

0      1     2     3     4    5   ...    8     9     10    11    12    13
0   1  14.23  1.71  2.43  15.6  127  ...  0.28  2.29  5.64  1.04  3.92  1065
1   1  13.20  1.78  2.14  11.2  100  ...  0.26  1.28  4.38  1.05  3.40  1050
2   1  13.16  2.36  2.67  18.6  101  ...  0.30  2.81  5.68  1.03  3.17  1185
3   1  14.37  1.95  2.50  16.8  113  ...  0.24  2.18  7.80  0.86  3.45  1480
4   1  13.24  2.59  2.87  21.0  118  ...  0.39  1.82  4.32  1.04  2.93   735

[5 rows x 14 columns]